fs:
  datadir: "~/pet-project/blockchain/.database"
core:
  block:
    reward: 100
    complexity: 1
  state:
    dbfile: "state.db"
node:
  sync:
    tickerDuration: 10
  miner:
    tickerDuration: 10
    address: "0x38c4ce5b96044e7ddd9ad95947178ed3436a4539"
  isBootstrap: false
  bootstrapNodes:
    -  host: "http://testnet.unigate.network"
  http:
    protocol: "http"
    host: "http://9488dda31f9d.ngrok.io"
    port: 8600
wallet:
  datadir: "~/pet-project/blockchain/.database"