name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: go test -coverprofile=coverage.out ./...

    - name: Coverage metrics
      run: go tool cover -func coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}'

    - name: Build
      run: go build -v ./cmd/go-chain/...